---
- name: deploy Expansion Explorer on EC2
  hosts: all
  remote_user: ubuntu
  become_user: ubuntu
  tasks:
    - name: Create swap file
      become: yes
      become_user: root
      command: dd if=/dev/zero of=/extraswap bs=1M count=512
      when: ansible_swaptotal_mb < 1

    - name: Make sure swap file has the right permissions
      become: yes
      become_user: root
      file:
        path: /extraswap
        mode: "0600"

    - name: Run mkswap
      become: yes
      become_user: root
      command: mkswap /extraswap
      when: ansible_swaptotal_mb < 1

    - name: Add swap to fstab
      become: yes
      become_user: root
      action: lineinfile dest=/etc/fstab regexp="extraswap" line="/extraswap none swap sw 0 0" state=present

    - name: Turn swap on
      become: yes
      become_user: root
      command: swapon -a

    - name: Add nodejs apt key
      become: yes
      become_user: root
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add nodejs 22.x ppa for apt repo
      become: yes
      become_user: root
      shell: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash - 

    - name: Install nodejs
      become: yes
      become_user: root
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install Git LFS
      become: yes
      become_user: root 
      ansible.builtin.apt:
        name: git-lfs
        state: present
        update_cache: yes

    - name: get latest github repo
      git:
        repo: https://github.com/transitmatters/expansion-explorer.git
        dest: /home/ubuntu/expansion-explorer
        force: yes
        version: "{{ branch | default('main') }}"

    - name: pull git LFS files
      command: git lfs pull
      args:
        chdir: /home/ubuntu/expansion-explorer

    - name: copy systemd service file
      become: yes
      become_user: root
      copy:
        src: systemd.conf
        dest: /etc/systemd/system/expansion-explorer.service

    - name: Install nginx
      become: yes
      become_user: root
      ansible.builtin.apt:
        name: nginx

    - name: copy nginx config file
      become: yes
      become_user: root
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-enabled/default

    - name: restart nginx
      become: yes
      become_user: root
      systemd:
        name: nginx
        state: restarted
        daemon_reload: yes

    - name: install app dependencies
      shell: npm ci
      args:
        chdir: /home/ubuntu/expansion-explorer

    - name: Make sure a service unit is running and enabled
      become: yes
      become_user: root
      ansible.builtin.systemd_service:
        state: started
        name: expansion-explorer
        enabled: true

    - name: restart service
      become: yes
      become_user: root
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: expansion-explorer
